/*
 * Frenny Smith De La Cruz All Rights Reserved <Propiedad Intelectual> *Solo personal autorizado*.
 * Matricula -> 100510483
 * UNIVERSIDAD AUTONOMA DE SANTO DOMINGO RECINTO UASD SAN FRANCISCO DE MACORIS (CURNE).
 */
package prjsistemaventas.Formularios;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import prjsistemaventas.Implementaciones.ProductosCRUDImp;
import prjsistemaventas.dao.Producto;

/**
 *
 * @author Frensth
 */
public class FrmBuscarProducto extends javax.swing.JFrame {

    private Producto producto;
    
    public FrmBuscarProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Cruzrojasinfondos.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btnSeleccionar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mSeleccionar = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Producto");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombres", "Laboratorio", "Precio", "Stock", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblProductos.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblProductos.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblProductos.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblProductos.getColumnModel().getColumn(4).setPreferredWidth(10);
            tblProductos.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 240));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 640, 240));

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnSeleccionar.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inspection-80_icon-icons.com_57310.png"))); // NOI18N
        btnSeleccionar.setFocusable(false);
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSeleccionar);

        btnSalir.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnSalir.setFocusable(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));

        jMenu1.setText("Archivo");

        mSeleccionar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/peques/Inspection-80_icon-icons.com_57310.png"))); // NOI18N
        mSeleccionar.setText("Seleccionar");
        mSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSeleccionarActionPerformed(evt);
            }
        });
        jMenu1.add(mSeleccionar);

        mSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/peques/salir.png"))); // NOI18N
        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarTabla()
    {
       
       DefaultTableModel modelo = (DefaultTableModel)tblProductos.getModel();
       
       
       for(int i = 0; i < modelo.getRowCount(); i++)
       {
           modelo.removeRow(i);
           i=i-1;
       }
           
           
        ArrayList<Producto> productoList = new ProductosCRUDImp().mostrarTodos();
        int contador = 0;
        
        for(Producto r : productoList)
        {
            
            Object celdas[] = new Object[6];
            celdas[0] = r.getCodigo();
            celdas[1] = r.getNombres();
            celdas[2] = r.getLaboratorio();
            celdas[3] = r.getPrecio();
            celdas[4] = r.getStock();
            celdas[5] = r.getEstado();
            
                    
            modelo.addRow(celdas);
            contador++;
        }
        
        
        tblProductos.setModel(modelo);
        
    }
    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_mSalirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
       if(producto != null)
        {
            FrmFormularioPrincipal.mantProducto.setTxt(producto);
            FrmFormularioPrincipal.transVenta.setTxtProducto(producto);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Debe seleccionar una opcion", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    
    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        int seleccionar = tblProductos.rowAtPoint(evt.getPoint());
        
        int codigo = Integer.valueOf(String.valueOf(tblProductos.getValueAt(seleccionar, 0)));
        String nombre = String.valueOf(tblProductos.getValueAt(seleccionar, 1));
        String laboratorio = String.valueOf(tblProductos.getValueAt(seleccionar, 2));
        double precio = Double.parseDouble(String.valueOf(tblProductos.getValueAt(seleccionar, 3)));        
        int stock = Integer.valueOf(String.valueOf(tblProductos.getValueAt(seleccionar, 4)));        
        char estado = String.valueOf(tblProductos.getValueAt(seleccionar, 5)).charAt(0);

        producto = new Producto(codigo, nombre, laboratorio, precio, stock, estado);
        
    }//GEN-LAST:event_tblProductosMouseClicked

    private void mSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSeleccionarActionPerformed
        if(producto != null)
        {
            FrmFormularioPrincipal.mantProducto.setTxt(producto);
            FrmFormularioPrincipal.transVenta.setTxtProducto(producto);
            this.dispose();
        
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Debe seleccionar una opcion", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_mSeleccionarActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenuItem mSeleccionar;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
