/*
 * Frenny Smith De La Cruz All Rights Reserved <Propiedad Intelectual> *Solo personal autorizado*.
 * Matricula -> 100510483
 * UNIVERSIDAD AUTONOMA DE SANTO DOMINGO RECINTO UASD SAN FRANCISCO DE MACORIS (CURNE).
 */
package prjsistemaventas.Formularios;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import prjsistemaventas.Implementaciones.UsuariosCRUDImp;
import prjsistemaventas.dao.Usuario;

/**
 *
 * @author Frensth
 */
public class FrmIniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form JFrIniciarSesion
     */
    public FrmIniciarSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Cruzrojasinfondos.png")).getImage());
        
    }
    
    private void iniciarSesion()
    {
        UsuariosCRUDImp usuariosBD = new UsuariosCRUDImp();
        ArrayList<Usuario> usuarios;
        String usuarioingresado = txtUsuario.getText();
        String contrasenia = String.valueOf(txtContrasenia.getPassword());
        Usuario user = new Usuario();
        
        
        usuarios = usuariosBD.mostrarTodos();
        
        for(Usuario u : usuarios)
        {
            
            if((u.getUsuario().equals(usuarioingresado) && u.getContrasenia().equals(contrasenia)))
            {
                user.setId(u.getId());
                user.setUsuario(u.getUsuario());
                user.setContrasenia(u.getContrasenia()); 
                
                
                //JOptionPane.showMessageDialog(null, "Usuario: " + user.getUsuario() + "\n" + "Contraseña: " + user.getContrasenia(), "Sesion iniciada", JOptionPane.INFORMATION_MESSAGE);
                
                FrmFormularioPrincipal frmPrinicipal = new FrmFormularioPrincipal(user);
                frmPrinicipal.setVisible(true);
                this.dispose();
                
                break;
            }
            else
            {
                lblError.setText("Usuario o contraseña incorrecta.");
            }
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JToggleButton();
        txtContrasenia = new javax.swing.JPasswordField();
        lblError = new javax.swing.JLabel();
        btnIniciarsesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel.setBackground(new java.awt.Color(190, 190, 190));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(24, 22, 22));
        jLabel1.setText("¡Bienvenido!");
        jPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, 40));

        txtUsuario.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        jPanel.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 210, 30));

        jLabel3.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(24, 22, 22));
        jLabel3.setText("Contraseña");
        jPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 90, 50));

        jLabel4.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(24, 22, 22));
        jLabel4.setText("Usuario");
        jPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 205, -1, 40));

        btnAyuda.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/info.png"))); // NOI18N
        btnAyuda.setAlignmentY(0.0F);
        btnAyuda.setContentAreaFilled(false);
        btnAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAyuda.setFocusable(false);
        btnAyuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAyuda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnAyuda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        jPanel.add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 40, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cruzrojasinfondos.png"))); // NOI18N
        jPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 150, -1));

        btnSalir.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnSalir.setAlignmentY(0.0F);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 70, 60));

        txtContrasenia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContrasenia.setToolTipText("");
        txtContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyReleased(evt);
            }
        });
        jPanel.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 210, 30));

        lblError.setBackground(new java.awt.Color(0, 0, 0));
        lblError.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 230, 20));

        btnIniciarsesion.setBackground(new java.awt.Color(242, 237, 237));
        btnIniciarsesion.setFont(new java.awt.Font("Gadugi", 0, 11)); // NOI18N
        btnIniciarsesion.setForeground(new java.awt.Color(14, 13, 13));
        btnIniciarsesion.setText("Iniciar Sesión");
        btnIniciarsesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarsesionActionPerformed(evt);
            }
        });
        jPanel.add(btnIniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 120, 30));

        getContentPane().add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        JOptionPane.showMessageDialog(this, "Si necesita ayuda para iniciar sesión o cualquier otra inquietud"
                + " comuniquese con el encargado del sistema.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAyudaActionPerformed

    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyReleased
        if(evt.getKeyChar() == '\n' )       
           iniciarSesion();
    }//GEN-LAST:event_txtUsuarioKeyReleased

    private void btnIniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarsesionActionPerformed
        iniciarSesion();
    }//GEN-LAST:event_btnIniciarsesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAyuda;
    private javax.swing.JButton btnIniciarsesion;
    private javax.swing.JToggleButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel lblError;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
